name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: pnpm/action-setup@v4.4.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm run knip
      - run: pnpm run build
      - run: pnpm run publint
      - run: pnpm run attw
      - run: pnpm test -- run
      - run: pnpm audit --prod --audit-level high
